version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: go-expo-chat-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database-data:/var/lib/postgresql/data

volumes:
  database-data:
